apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-java-deploy-test
  name: k8s-java-deploy-test
  namespace: dev-project
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: k8s-java-deploy-test
  template:
    metadata:
      labels:
        app: k8s-java-deploy-test
    spec:
      imagePullSecrets:
        - name: $REGISTRY_CREDENTIAL_ID
      containers:
        - image: $REGISTRY_ADDRESS/$REGISTRY_NAMESPACE/$APP_NAME:$TAG_NAME-$BUILD_NUMBER
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 8080
          #  timeoutSeconds: 10
          #  failureThreshold: 30
          #  periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dev-mysql-env
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30