[log]
devMode=true
level="Debug"
path="./logs/"
save=1

[db]
dbType="mysql"
username="root"
password="root"
host="www.laoxin.com"
port=3306
dB="poseidon"
param="charset=utf8"
showSql=true
maxIdleConns=10
maxOpenConns=10
connMaxLifetime=10


[project]
serverPort=8080
excludeAuthUrls=["/"]
allowMaxDelay=-60
